services:
  github-runner:
    image: myoung34/github-runner:latest
    container_name: github-runner
    restart: always
    environment:
      - REPO_URL=https://github.com/Nejwid/NP
      - RUNNER_TOKEN=A6LUGTM3DCDTDVWAXEMBYYTJNF6DC
      - RUNNER_NAME=self-hosted-docker
      - RUNNER_LABELS=self-hosted,docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      /bin/bash -c "
        apt-get update && 
        apt-get install -y maven &&
        /entrypoint.sh"
