name: openobserve
services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:v0.40.0
    container_name: openobserve
    environment:
      - ZO_DATA_DIR=/data
      - ZO_ROOT_USER_EMAIL=root@example.com
      - ZO_ROOT_USER_PASSWORD=pass
    volumes:
      - "./data:/data"
    ports:
      - "5080:5080"
