services:
  github-runner:
    image: myoung34/github-runner:latest
    container_name: github-runner
    restart: always
    environment:
      - REPO_URL=https://github.com/USER/REPO
      - RUNNER_TOKEN=XXXXXXX
      - RUNNER_NAME=self-hosted-docker
      - RUNNER_LABELS=self-hosted,docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
