concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
session_timeout = 1800

[[runners]]
name = "gitlab-runner"
url = "http://host.docker.internal:4321/"
id = 2
token = "glrtr-moOM0fqlA0q3adQ54FMy2W86MQpwOjEKdDozCw.01.120u249at"
executor = "docker"

[runners.cache]
MaxUploadedArchiveSize = 0

[runners.docker]
tls_verify = false
image = "maven:3.9-eclipse-temurin-17"
privileged = true
disable_entrypoint_overwrite = false
oom_kill_disable = false
disable_cache = false
shm_size = 0
network_mtu = 0

extra_hosts = ["host.docker.internal:host-gateway"]
volumes = [
  "/var/run/docker.sock:/var/run/docker.sock",
  "/cache"
]
